require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FeedbackPagesController do

  # This should return the minimal set of attributes required to create a valid
  # FeedbackPage. As you add validations to FeedbackPage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "url" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FeedbackPagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all feedback_pages as @feedback_pages" do
      page = FeedbackPage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:feedback_pages).should eq([page])
    end
  end

  describe "GET show" do
    it "assigns the requested feedback_page as @feedback_page" do
      page = FeedbackPage.create! valid_attributes
      get :show, {:id => page.to_param}, valid_session
      assigns(:feedback_page).should eq(page)
    end
  end

  describe "GET new" do
    it "assigns a new feedback_page as @feedback_page" do
      get :new, {}, valid_session
      assigns(:feedback_page).should be_a_new(FeedbackPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested feedback_page as @feedback_page" do
      page = FeedbackPage.create! valid_attributes
      get :edit, {:id => page.to_param}, valid_session
      assigns(:feedback_page).should eq(page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FeedbackPage" do
        expect {
          post :create, {:feedback_page => valid_attributes}, valid_session
        }.to change(FeedbackPage, :count).by(1)
      end

      it "assigns a newly created feedback_page as @feedback_page" do
        post :create, {:feedback_page => valid_attributes}, valid_session
        assigns(:feedback_page).should be_a(FeedbackPage)
        assigns(:feedback_page).should be_persisted
      end

      it "redirects to the created feedback_page" do
        post :create, {:feedback_page => valid_attributes}, valid_session
        response.should redirect_to(FeedbackPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved feedback_page as @feedback_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        FeedbackPage.any_instance.stub(:save).and_return(false)
        post :create, {:feedback_page => { "url" => "invalid value" }}, valid_session
        assigns(:feedback_page).should be_a_new(FeedbackPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FeedbackPage.any_instance.stub(:save).and_return(false)
        post :create, {:feedback_page => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested feedback_page" do
        page = FeedbackPage.create! valid_attributes
        # Assuming there are no other feedback_pages in the database, this
        # specifies that the FeedbackPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FeedbackPage.any_instance.should_receive(:update_attributes).with({ "url" => "MyString" })
        put :update, {:id => page.to_param, :feedback_page => { "url" => "MyString" }}, valid_session
      end

      it "assigns the requested feedback_page as @feedback_page" do
        page = FeedbackPage.create! valid_attributes
        put :update, {:id => page.to_param, :feedback_page => valid_attributes}, valid_session
        assigns(:feedback_page).should eq(page)
      end

      it "redirects to the feedback_page" do
        page = FeedbackPage.create! valid_attributes
        put :update, {:id => page.to_param, :feedback_page => valid_attributes}, valid_session
        response.should redirect_to(page)
      end
    end

    describe "with invalid params" do
      it "assigns the feedback_page as @feedback_page" do
        page = FeedbackPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FeedbackPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => page.to_param, :feedback_page => { "url" => "invalid value" }}, valid_session
        assigns(:feedback_page).should eq(page)
      end

      it "re-renders the 'edit' template" do
        page = FeedbackPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FeedbackPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => page.to_param, :feedback_page => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested feedback_page" do
      page = FeedbackPage.create! valid_attributes
      expect {
        delete :destroy, {:id => page.to_param}, valid_session
      }.to change(FeedbackPage, :count).by(-1)
    end

    it "redirects to the feedback_pages list" do
      page = FeedbackPage.create! valid_attributes
      delete :destroy, {:id => page.to_param}, valid_session
      response.should redirect_to(pages_url)
    end
  end

end
